### ISSUE TITLE
uGuiSetSelectedGameObject missing Finish() event

### ISSUE THREAD

**Issue by jeanfabre** [jeanfabre/PlayMaker--Unity--UI#1]
Hi,

 Noticed that the action doesn't send a Finish() when done, this is important to add this for every action when done, so that the state itself can fire a "FINISH" transition if/when required.

Bye,

 Jean

**Comment by djaydino** [comment]
hi,
It was not my script and i did not check it well enough :)
I have added finish(); to the script, but it still has to be added to ugui package witch i don't know yet how to do.

greetings,

Dino

**Comment by jeanfabre** [comment]
Hi,

 No worries. It's actually great that you help contributing on the ecosystem. It's very much appreciated indeed!

To add to the package, you need to have uTomate, which then gives you access to the utomate plans on publishing packages with premade settings ( so that you publish in one click basically, without worrying of what to include, what to exclude, the naming convention, folder to save, etc, all this is dealt with once for all in a uTomate plan)

http://www.ancientlightstudios.com/utomate/

but don't worry, I'll push it myself.

 Bye,

 Jean
