### ISSUE TITLE
uGuiProxyFull.unitypackage have a small typo

### ISSUE THREAD

**Issue by Salja** [jeanfabre/PlayMaker--Unity--UI#2]
Hey first sorry for my bad english im from german and my english is bad 🗡 

The uGuiProxyFull.unitypackage have a small issues

After Import come a error https://prnt.sc/fgzbej

`Assets/PlayMaker Custom Actions/uGui/EventSystem/uGuiOnDragEvent.cs(12,15): error CS0101: The namespace `HutongGames.PlayMaker.Actions' already contains a definition for `uGuiGetSelectedGameObject'`

The Problem Comes from this file `uGuiOnDragEvent.cs`

On Github is the file not more Exits look here https://prnt.sc/fgzbax

only the uGuiProxyFull.unitypackage have the file into http://prntscr.com/fgzawa

i hope you can fix thank you and sorry for my bad english

**Comment by jeanfabre** [comment]
Hi,

 you likely have a duplicate of uGuiGetSelectedGameObject in your project, can you double check and search in your assets with "uGuiGetSelectedGameObject" it should list only one.

 let me know how it goes.

 Bye,

 Jean

**Comment by Salja** [comment]
Thats what im say uGuiOnDragEvent have this uGuiGetSelectedGameObject in the source code

**Comment by Salja** [comment]
uGuiGetSelectedGameObject have uGuiGetSelectedGameObject as class and uGuiOnDragEvent have the same class

and the file uGuiOnDragEvent is not more on github only in the unity.packet file

**Comment by jeanfabre** [comment]
ahh! d'oh :)

yes, I am correcting this right now.

**Comment by Salja** [comment]
sorry again for my bad english but i sure you have understand hrhr

Thank you

**Comment by jeanfabre** [comment]
Ok,  can you try now to updated from the ecosystem?, I repackaged

**Comment by Salja** [comment]
The Error is fixed but now new error http://prntscr.com/fgzkhk

**Comment by jeanfabre** [comment]
Hi,

 you need to run the Unity updater ( menu Assets/Run API updater)

Bye,

 Jean

**Comment by Salja** [comment]
Perfect thank you
