### ISSUE TITLE
Error after Unet Submodul install

### ISSUE THREAD

**Issue by Salja** [jeanfabre/PlayMaker--Unity--UI#3]
After Install the Playmaker Unet Submodul i have Errors on the GUI Actions 
http://prntscr.com/fo2mo3

thanks

**Comment by Salja** [comment]
hmmm

**Comment by jeanfabre** [comment]
Hi,

 yes, I need to repackage uNet, for now ( until I repakage), simply install uGui package, it will then work.

**Comment by Salja** [comment]
Thanks
